//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxialPumps
    {
        public int Id { get; set; }
        public string StandartSize { get; set; }
        public int InningsMin { get; set; }
        public Nullable<int> InningsMax { get; set; }
        public decimal PressureMin { get; set; }
        public Nullable<decimal> PressureMax { get; set; }
        public decimal AcceptableCavitationStockMin { get; set; }
        public Nullable<decimal> AcceptableCavitationStockMax { get; set; }
        public int IdFrequencyRotation { get; set; }
        public int PowerConsumptionMin { get; set; }
        public Nullable<int> PowerConsumptionMax { get; set; }
        public int IdEfficiencyMin { get; set; }
        public Nullable<decimal> EfficiencyMax { get; set; }
    }
}
