//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boilers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Perfomance { get; set; }
        public int Type { get; set; }
    
        public virtual TypeOfBoilers TypeOfBoilers { get; set; }
    }
}
