//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calciners
    {
        public int Id { get; set; }
        public int Performance { get; set; }
        public int Diameter { get; set; }
        public decimal CrossAreaSections { get; set; }
        public int AirFlow { get; set; }
    }
}
