//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrifugalPumps
    {
        public int Id { get; set; }
        public string StandartSize { get; set; }
        public int Innings { get; set; }
        public decimal Pressure { get; set; }
        public Nullable<int> AcceptableCavitationStock { get; set; }
        public int IdFrequencyRotation { get; set; }
        public int PowerConsumption { get; set; }
        public int Efficiency { get; set; }
    }
}
