//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoolingWaterFlowOnTurbine
    {
        public int Id { get; set; }
        public string TurbineName { get; set; }
        public int WaterConsumption { get; set; }
        public int Perfomance { get; set; }
        public int TurbineType { get; set; }
        public Nullable<int> WaterConsumptionForNetworkHeaters { get; set; }
    }
}
