//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoolingTowers
    {
        public int Id { get; set; }
        public int SquareSpinkler { get; set; }
        public Nullable<int> PerfomanceMin { get; set; }
        public Nullable<int> PerfomanceMax { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Base { get; set; }
        public Nullable<decimal> Estuary { get; set; }
    }
}
