//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeCapacityAndReagentConsumptionFSD
    {
        public int Id { get; set; }
        public int IdIonFiltersNames { get; set; }
        public int IdBrandUseIon { get; set; }
        public int WorkingExchangeCapacity { get; set; }
        public int IdNameReagentFirst { get; set; }
        public int IdNameReagentSecond { get; set; }
        public decimal SpecificConsumptionFirst { get; set; }
        public decimal SpecificConsumptionSecond { get; set; }
    
        public virtual BrandUseIon BrandUseIon { get; set; }
        public virtual IonFiltersNames IonFiltersNames { get; set; }
        public virtual NameReagent NameReagent { get; set; }
    }
}
