//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filters
    {
        public int Id { get; set; }
        public int IdApplyingFilters { get; set; }
        public Nullable<int> IdFilterTypes { get; set; }
        public string Cipheer { get; set; }
        public Nullable<int> IdOperatingPressure { get; set; }
        public int Diameter { get; set; }
        public Nullable<int> FilterLoadHeight { get; set; }
        public Nullable<int> WaterConsumption { get; set; }
    
        public virtual ApplyingFilter ApplyingFilter { get; set; }
        public virtual FilterType FilterType { get; set; }
        public virtual OperatingPressure OperatingPressure { get; set; }
    }
}
