//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroVisionFW.Model.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterConsumptionForOwnNeeds
    {
        public int Id { get; set; }
        public int IdNameIonFilter { get; set; }
        public int IdBrandUseIon { get; set; }
        public decimal WaterConsumptionForPreparationOfRegenerationSolutions { get; set; }
        public decimal WaterConsumptionForWashingProductsRegeneration { get; set; }
        public decimal GeneralWaterConsumption { get; set; }
    
        public virtual BrandUseIon BrandUseIon { get; set; }
        public virtual IonFiltersNames IonFiltersNames { get; set; }
    }
}
